--- 
title: "What They Forgot to Teach You About R Book Club"
author: "The Data Science Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-rwtf
description: "This is the product of the Data Science Learning Community's What They Forgot to Teach You About R Book Club."
---

# Welcome {-}

Welcome to the bookclub! 

This is a companion for the book [_What They Forgot to Teach You About R_](https://rstats.wtf/) by Jenny Bryan and Jim Hester.
This companion is available at [dslc.io/rwtf](https://dslc.io/rwtf).

Also see the [Workshop](https://github.com/rstats-wtf/wtf-2022-rsc).

This website is being developed by the [Data Science Learning Community](https://dslc.io). Follow along, and [join the community](https://dslc.io/join) to participate.

This companion follows the [Data Science Learning Community Code of Conduct](https://dslc.io/conduct).

## Book club meetings {-}

- Each week, a volunteer will present a chapter from the book (or part of a chapter).
  - **This is the best way to learn the material.**
- Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
- More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-rwtf).
- Presentations will be recorded, and will be available on the [Data Science Learning Community YouTube Channel](https://dslc.io/youtube).

## Pace {-}

- We'll _try_ to cover 1 chapter/week, but...
    - ...It's ok to split chapters when they feel like too much...
    - ...And some "chapters" don't have any content.
- We will try to meet every week, but will take some breaks for holidays, etc.


## Setting Up {-}

-   GitHub: See [DSLC Setup Repo](https://github.com/r4ds/bookclub-setup) for latest instructions
-   Other stuff: Run `devtools::has_devel()`
-   Everyone should run these things in session 0. Let's help each other get up and running!
