on:
  pull_request:
    branches: main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  pr_check:
    name: pr_check
    runs-on: ubuntu-latest
    steps:
      - name: render_book
      - run: 'echo "No build required" '
