name: pr_check
on:
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  bookdown:
    uses: r4ds/r4dsactions/.github/workflows/render_club_pr.yml@main
